export const htmlQuestions = [
  {
    id: 1,
    text: "Which of the following input control represents a date consisting of a year and a week number encoded according to ISO 8601 in Web Form 2.0?",
    options: {
      A: "week",
      B: "time",
      C: "number",
      D: "range",
    },
    correctAnswer: "A",
  },
  {
    id: 2,
    text: "Which of the following input control represents a time (hour, minute, seconds, fractional seconds) encoded according to ISO 8601 in Web Form 2.0?",
    options: {
      A: "week",
      B: "time",
      C: "number",
      D: "range",
    },
    correctAnswer: "B",
  },
  {
    id: 3,
    text: "Which of the following input control accepts only numerical value in Web Form 2.0?",
    options: {
      A: "week",
      B: "time",
      C: "number",
      D: "range",
    },
    correctAnswer: "C",
  },
  {
    id: 4,
    text: "Which of the following input control is used for input fields that should contain a value from a range of numbers in Web Form 2.0?",
    options: {
      A: "week",
      B: "time",
      C: "number",
      D: "range",
    },
    correctAnswer: "D",
  },
  {
    id: 5,
    text: "Which of the following input control is used for input fields that should contain an e-mail address in Web Form 2.0?",
    options: {
      A: "email",
      B: "url",
      C: "number",
      D: "range",
    },
    correctAnswer: "A",
  },
  {
    id: 6,
    text: "Which of the following input control is used for input fields that should contain an URL address in Web Form 2.0?",
    options: {
      A: "email",
      B: "url",
      C: "number",
      D: "range",
    },
    correctAnswer: "B",
  },
  {
    id: 7,
    text: "Which of the following tag is used to represent the result of different types of output in HTML5?",
    options: {
      A: "output",
      B: "placeholder",
      C: "autofocus",
      D: "required",
    },
    correctAnswer: "A",
  },
  {
    id: 8,
    text: "Which of the following tag provides a hint to the user of what can be entered in the field in HTML5?",
    options: {
      A: "output",
      B: "placeholder",
      C: "autofocus",
      D: "required",
    },
    correctAnswer: "B",
  },
  {
    id: 9,
    text: "Which of the following tag automatically focus one particular form field in HTML5?",
    options: {
      A: "output",
      B: "placeholder",
      C: "autofocus",
      D: "required",
    },
    correctAnswer: "C",
  },
  {
    id: 10,
    text: "Which of the following tag insists to have a value in an input control in HTML5?",
    options: {
      A: "output",
      B: "placeholder",
      C: "autofocus",
      D: "required",
    },
    correctAnswer: "D",
  },
  {
    id: 11,
    text: "Can you use SVG tags directly in HTML5 without any plugin?",
    options: {
      A: "true",
      B: "false",
    },
    correctAnswer: "A",
  },
  {
    id: 12,
    text: "Can you use MathML tags directly in HTML5 without any plugin?",
    options: {
      A: "true",
      B: "false",
    },
    correctAnswer: "A",
  },
  {
    id: 13,
    text: "Which of the following is true about Cookies?",
    options: {
      A: "Cookies are included with every HTTP request, thereby slowing down your web application by transmitting the same data.",
      B: "Cookies are included with every HTTP request, thereby sending data unencrypted over the internet.",
      C: "Cookies are limited to about 4 KB of data . Not enough to store required data.",
      D: "All of the above.",
    },
    correctAnswer: "D",
  },
  {
    id: 14,
    text: "Which of the following is true about Session Storage in HTML5?",
    options: {
      A: "HTML5 introduces the sessionStorage attribute which would be used by the sites to add data to the session storage.",
      B: "It will be accessible to any page from the same site opened in that window i.e. session.",
      C: "As soon as you close the window, session would be lost.",
      D: "All of the above.",
    },
    correctAnswer: "D",
  },
  {
    id: 15,
    text: "Which of the following is true about Local Storage in HTML5?",
    options: {
      A: "HTML5 introduces the localStorage attribute which would be used to access a page's local storage area without no time limit.",
      B: "this local storage will be available whenever you would use that page.",
      C: "Both of the above.",
      D: "None of the above.",
    },
    correctAnswer: "C",
  },
  {
    id: 16,
    text: "When a session storage data gets deleted in HTML5?",
    options: {
      A: "The Session Storage Data would be deleted by the browsers immediately after the session gets terminated.",
      B: "If you want to clear all settings, you need to call localStorage.clear() method.",
      C: "Both of the above.",
      D: "None of the above.",
    },
    correctAnswer: "A",
  },
  {
    id: 17,
    text: "How to delete a local storage data in HTML5?",
    options: {
      A: "To clear a local storage setting you would need to call localStorage.remove('key'); where 'key' is the key of the value you want to remove.",
      B: "If you want to clear all settings, you need to call localStorage.clear() method.",
      C: "Both of the above.",
      D: "None of the above.",
    },
    correctAnswer: "C",
  },
  {
    id: 18,
    text: "Which of the following is correct about Server Side Events(SSE) in HTML5?",
    options: {
      A: "Using SSE you can push DOM events continously from your web server to the visitor's browser.",
      B: "The event streaming approach opens a persistent connection to the server, sending data to the client when new information is available, eliminating the need for continuous polling.",
      C: "Server-sent events standardizes how we stream data from the server to the client.",
      D: "All of the above.",
    },
    correctAnswer: "D",
  },
  {
    id: 19,
    text: "Which of the following is correct about Server Side Events(SSE) in HTML5?",
    options: {
      A: "To use Server-Sent Events in a web application, you would need to add an <eventsource> element to the document.",
      B: "The src attribute of <eventsource> element should point to an URL which should provide a persistent HTTP connection that sends a data stream containing the events.",
      C: "The URL would point to a PHP, PERL or any Python script which would take care of sending event data consistently.",
      D: "All of the above.",
    },
    correctAnswer: "D",
  },
  {
    id: 20,
    text: "Which of the following is correct Content-type header that a server side script should send for SSE in HTML5?",
    options: {
      A: "Content-Type: text/event-stream",
      B: "Content-Type: text/application-stream",
      C: "Content-Type: text/data-stream",
      D: "None of the above.",
    },
    correctAnswer: "A",
  },
  {
    id: 21,
    text: "Which of the following is correct about WebSockets in HTML5?",
    options: {
      A: "Web Sockets is a next-generation bidirectional communication technology for web applications which operates over a single socket and is exposed via a JavaScript interface in HTML 5 compliant browsers.",
      B: "Once you get a Web Socket connection with the web server, you can send data from browser to server by calling a send() method, and receive data from server to browser by an onmessage event handler.",
      C: "Both of the above.",
      D: "None of the above.",
    },
    correctAnswer: "C",
  },
  {
    id: 22,
    text: "Which value of Socket.readyState atribute of WebSocket indicates that the connection has not yet been established?",
    options: {
      A: "0",
      B: "1",
      C: "2",
      D: "3",
    },
    correctAnswer: "A",
  },
  {
    id: 23,
    text: "Which value of Socket.readyState atribute of WebSocket indicates that the connection is established and communication is possible?",
    options: {
      A: "0",
      B: "1",
      C: "2",
      D: "3",
    },
    correctAnswer: "B",
  },
  {
    id: 24,
    text: "Which value of Socket.readyState atribute of WebSocket indicates that the connection is going through the closing handshake?",
    options: {
      A: "0",
      B: "1",
      C: "2",
      D: "3",
    },
    correctAnswer: "C",
  },
  {
    id: 25,
    text: "Which value of Socket.readyState atribute of WebSocket indicates that the connection has been closed or could not be opened?",
    options: {
      A: "0",
      B: "1",
      C: "2",
      D: "3",
    },
    correctAnswer: "D",
  },
  {
    id: 26,
    text: "Which of the following is true about HTML 5?",
    options: {
      A: "HTML5 is the next major revision of the HTML standard superseding HTML 4.01, XHTML 1.0, and XHTML 1.1.",
      B: "HTML5 is a standard for structuring and presenting content on the World Wide Web.",
      C: "HTML5 is a cooperation between the World Wide Web Consortium (W3C) and the Web Hypertext Application Technology Working Group (WHATWG).",
      D: "All of the above.",
    },
    correctAnswer: "D",
  },
  {
    id: 27,
    text: "Which of the following feature is a part of HTML 5?",
    options: {
      A: "Persistent Local Storage",
      B: "WebSocket",
      C: "Server-Sent Events",
      D: "All of the above.",
    },
    correctAnswer: "D",
  },
  {
    id: 28,
    text: "Which of the following feature is a part of HTML 5?",
    options: {
      A: "Canvas",
      B: "Audio & Video",
      C: "Geolocation",
      D: "All of the above.",
    },
    correctAnswer: "D",
  },
  {
    id: 29,
    text: "Which of the following browser supports HTML5 in its latest version?",
    options: {
      A: "Apple Safari",
      B: "Google Chrome",
      C: "Both of the above.",
      D: "None of the above.",
    },
    correctAnswer: "C",
  },
  {
    id: 30,
    text: "Which of the following browser supports HTML5 in its latest version?",
    options: {
      A: "Mozilla Firefox",
      B: "Opera",
      C: "Both of the above.",
      D: "None of the above.",
    },
    correctAnswer: "C",
  },
  {
    id: 31,
    text: "Is HTML5 backward compatible with old browsers?",
    options: {
      A: "true",
      B: "false",
    },
    correctAnswer: "A",
  },
  {
    id: 32,
    text: "Are HTML tags case sensitive?",
    options: {
      A: "true",
      B: "false",
    },
    correctAnswer: "B",
  },
  {
    id: 33,
    text: "Which of the following tag represents a generic document or application section in HTML5?",
    options: {
      A: "section",
      B: "article",
      C: "aside",
      D: "header",
    },
    correctAnswer: "A",
  },
  {
    id: 34,
    text: "Which of the following tag represents an independent piece of content of a document in HTML5?",
    options: {
      A: "section",
      B: "article",
      C: "aside",
      D: "header",
    },
    correctAnswer: "B",
  },
  {
    id: 35,
    text: "Which of the following tag represents a piece of content that is only slightly related to the rest of the page in HTML5?",
    options: {
      A: "section",
      B: "article",
      C: "aside",
      D: "header",
    },
    correctAnswer: "C",
  },
  {
    id: 36,
    text: "Which of the following tag represents the header of a section in HTML5?",
    options: {
      A: "section",
      B: "article",
      C: "aside",
      D: "header",
    },
    correctAnswer: "D",
  },
  {
    id: 37,
    text: "Which of the following tag represents the footer of a section in HTML5?",
    options: {
      A: "footer",
      B: "nav",
      C: "section",
      D: "dialog",
    },
    correctAnswer: "A",
  },
  {
    id: 38,
    text: "Which of the following tag represents a section of the document intended for navigation in HTML5?",
    options: {
      A: "footer",
      B: "nav",
      C: "section",
      D: "dialog",
    },
    correctAnswer: "B",
  },
  {
    id: 39,
    text: "Which of the following tag can be used to mark up a conversation in HTML5?",
    options: {
      A: "footer",
      B: "nav",
      C: "dialog",
      D: "figure",
    },
    correctAnswer: "C",
  },
  {
    id: 40,
    text: "Which of the following tag can be used to associate a caption together with some embedded content in HTML5?",
    options: {
      A: "footer",
      B: "nav",
      C: "dialog",
      D: "figure",
    },
    correctAnswer: "D",
  },
  {
    id: 41,
    text: "Which of the following is correct about custom attributes in HTML5?",
    options: {
      A: "A custom data attribute starts with data- and would be named based on your requirement.",
      B: "You would be able to get the values of these attributes using JavaScript APIs or CSS in similar way as you get for standard attributes.",
      C: "Both of the above.",
      D: "None of the above.",
    },
    correctAnswer: "C",
  },
  {
    id: 42,
    text: "Which of the following is correct about Web form 2.0 in HTML5?",
    options: {
      A: "Web Forms 2.0 is an extension to the forms features found in HTML4.",
      B: "Form elements and attributes in HTML5 provide a greater degree of semantic mark-up than HTML4.",
      C: "Form elements and attributes in HTML5 remove a great deal of the need for tedious scripting and styling that was required in HTML4.",
      D: "All of the above.",
    },
    correctAnswer: "D",
  },
  {
    id: 43,
    text: "Which of the following input control represents a date and time (year, month, day, hour, minute, second, fractions of a second) encoded according to ISO 8601 with the time zone set to UTC in Web Form 2.0?",
    options: {
      A: "datetime",
      B: "datetime-local",
      C: "date",
      D: "month",
    },
    correctAnswer: "A",
  },
  {
    id: 44,
    text: "Which of the following input control represents a date and time encoded according to ISO 8601 with no time zone information in Web Form 2.0?",
    options: {
      A: "datetime",
      B: "datetime-local",
      C: "date",
      D: "month",
    },
    correctAnswer: "B",
  },
  {
    id: 45,
    text: "Which of the following input control represents a date (year, month, day) encoded according to ISO 8601 in Web Form 2.0?",
    options: {
      A: "datetime",
      B: "datetime-local",
      C: "date",
      D: "month",
    },
    correctAnswer: "C",
  },
  {
    id: 46,
    text: "Which of the following is true about 'canvas' tag in HTML5?",
    options: {
      A: "HTML5 element <canvas> gives you an easy and powerful way to draw graphics using JavaScript.",
      B: "It can be used to draw graphs, make photo compositions or do simple (and not so simple) animations.",
      C: "Both of the above.",
      D: "None of the above.",
    },
    correctAnswer: "C",
  },
  {
    id: 47,
    text: "Which of the following is true about 'audio' tag in HTML5?",
    options: {
      A: "HTML5 supports <audio> tag which is used to embed sound content in an HTML or XHTML document.",
      B: "The current HTML5 draft specification does not specify which audio formats browsers should support in the audio tag.",
      C: "Both of the above.",
      D: "None of the above.",
    },
    correctAnswer: "C",
  },
  {
    id: 48,
    text: "Which of the following is true about 'audio' tag in HTML5?",
    options: {
      A: "Commonly used audio formats ogg, mp3 and wav are supported.",
      B: "You can use <source> tag to specify media along with media type and many other attributes.",
      C: "An audio element allows multiple source elements and browser will use the first recognized format.",
      D: "All of the above.",
    },
    correctAnswer: "D",
  },
  {
    id: 49,
    text: "Which of the following is true about 'video' tag in HTML5?",
    options: {
      A: "HTML5 supports <video> tag which is used to embed a video file in an HTML or XHTML document.",
      B: "The current HTML5 draft specification does not specify which video formats browsers should support in the video tag.",
      C: "Ogg files with Thedora video codec and Vorbis audio codec are supported.",
      D: "All of the above.",
    },
    correctAnswer: "D",
  },
  {
    id: 50,
    text: "Which of the following is true about 'video' tag in HTML5?",
    options: {
      A: "MPEG4 files with H.264 video codec and AAC audio codec are supported.",
      B: "You can use <source> tag to specify media along with media type and many other attributes.",
      C: "An video element allows multiple source elements and browser will use the first recognized format.",
      D: "All of the above.",
    },
    correctAnswer: "D",
  },
  {
    id: 51,
    text: "Which of the following is correct about geolocation api in HTML5?",
    options: {
      A: "HTML5 Geolocation API lets you share your location with your favorite web sites.",
      B: "A Javascript can capture your latitude and longitude and can be sent to backend web server and do fancy location-aware things like finding local businesses or showing your location on a map.",
      C: "Today most of the browsers and mobile devices support Geolocation API.",
      D: "All of the above.",
    },
    correctAnswer: "D",
  },
  {
    id: 52,
    text: "Which of the following method returns a geolocation object in HTML5?",
    options: {
      A: "navigator.geolocation",
      B: "browser.geolocation",
      C: "API.geolocation",
      D: "None of the above",
    },
    correctAnswer: "A",
  },
  {
    id: 53,
    text: "Which of the following method retrieves the current geographic location of the user?",
    options: {
      A: "geolocation.getCurrentPosition()",
      B: "geolocation.watchPosition()",
      C: "geolocation.clearPosition()",
      D: "None of the above",
    },
    correctAnswer: "A",
  },
  {
    id: 54,
    text: "Which of the following method cancels an ongoing watchPosition call?",
    options: {
      A: "geolocation.getCurrentPosition()",
      B: "geolocation.watchPosition()",
      C: "geolocation.clearPosition()",
      D: "None of the above",
    },
    correctAnswer: "C",
  },
  {
    id: 55,
    text: "Which of the following is correct about web workers in HTML5?",
    options: {
      A: "Web Workers do all the computationally expensive tasks without interrupting the user interface and typically run on separate threads.",
      B: "Web Workers allow for long-running scripts that are not interrupted by scripts that respond to clicks or other user interactions.",
      C: "Web Workers allow long tasks to be executed without yielding to keep the page responsive.",
      D: "All of the above.",
    },
    correctAnswer: "D",
  },
  {
    id: 56,
    text: "Which of the following attribute specifies a keyboard shortcut to access an element in HTML5?",
    options: {
      A: "accesskey",
      B: "key",
      C: "contextmenu",
      D: "contextkey",
    },
    correctAnswer: "A",
  },
  {
    id: 57,
    text: "Which of the following attribute specifies if the user can edit the element's content or not?",
    options: {
      A: "editable",
      B: "contenteditable",
      C: "contextmenu",
      D: "content",
    },
    correctAnswer: "B",
  },
  {
    id: 58,
    text: "Which of the following attribute specifies the context menu for an element?",
    options: {
      A: "key",
      B: "contextcontent",
      C: "contextmenu",
      D: "context",
    },
    correctAnswer: "C",
  },
  {
    id: 59,
    text: "Which of the following attribute specifies whether or not a user is allowed to drag an element?",
    options: {
      A: "drag",
      B: "content",
      C: "context",
      D: "draggable",
    },
    correctAnswer: "D",
  },
  {
    id: 60,
    text: "Which of the following attribute is used to group elements?",
    options: {
      A: "item",
      B: "itemprop",
      C: "itemcheck",
      D: "itemgroup",
    },
    correctAnswer: "A",
  },
  {
    id: 61,
    text: "Which of the following attribute is used to group items?",
    options: {
      A: "item",
      B: "itemprop",
      C: "itemcheck",
      D: "itemgroup",
    },
    correctAnswer: "B",
  },
  {
    id: 62,
    text: "Which of the following attribute specifies if the element must have it's spelling or grammar checked?",
    options: {
      A: "item",
      B: "itemcheck",
      C: "spellcheck",
      D: "itemgroup",
    },
    correctAnswer: "C",
  },
  {
    id: 63,
    text: "Which of the following attribute triggers event when the document goes offline?",
    options: {
      A: "offline",
      B: "off",
      C: "out",
      D: "onbeforeonload",
    },
    correctAnswer: "A",
  },
  {
    id: 64,
    text: "Which of the following attribute triggers an abort event?",
    options: {
      A: "offline",
      B: "onabort",
      C: "abort",
      D: "onbeforeonload",
    },
    correctAnswer: "B",
  },
  {
    id: 65,
    text: "Which of the following attribute triggers event after the document is printed?",
    options: {
      A: "offlineprint",
      B: "onprint",
      C: "onafterprint",
      D: "onbeforeprint",
    },
    correctAnswer: "C",
  },
  {
    id: 66,
    text: "Which of the following attribute triggers event before the document loads?",
    options: {
      A: "offline",
      B: "onabort",
      C: "onload",
      D: "onbeforeonload",
    },
    correctAnswer: "D",
  },
  {
    id: 67,
    text: "Which of the following attribute triggers event before the document is printed?",
    options: {
      A: "onbeforeprint",
      B: "onafterprint",
      C: "onprint",
      D: "beforeprint",
    },
    correctAnswer: "A",
  },
  {
    id: 68,
    text: "Which of the following attribute triggers event when the window loses focus?",
    options: {
      A: "onbeforeload",
      B: "onblur",
      C: "onlostfocus",
      D: "lostfocus",
    },
    correctAnswer: "B",
  },
  {
    id: 69,
    text: "Which of the following attribute triggers event when media can start play, but might has to stop for buffering?",
    options: {
      A: "onbeforeplay",
      B: "onplay",
      C: "oncanplay",
      D: "oncanplaythrough",
    },
    correctAnswer: "C",
  },
  {
    id: 70,
    text: "Which of the following attribute triggers event when media can be played to the end, without stopping for buffering?",
    options: {
      A: "onbeforeplay",
      B: "onplay",
      C: "oncanplay",
      D: "oncanplaythrough",
    },
    correctAnswer: "D",
  },
  {
    id: 71,
    text: "Which of the following attribute triggers event when a context menu is triggered?",
    options: {
      A: "oncontextmenu",
      B: "ondrag",
      C: "ondragend",
      D: "ondragenter",
    },
    correctAnswer: "A",
  },
  {
    id: 72,
    text: "Which of the following attribute triggers event when an element is dragged?",
    options: {
      A: "ondragleave",
      B: "ondrag",
      C: "ondragend",
      D: "ondragenter",
    },
    correctAnswer: "B",
  },
  {
    id: 73,
    text: "Which of the following attribute triggers event at the end of a drag operation?",
    options: {
      A: "ondragleave",
      B: "ondrag",
      C: "ondragend",
      D: "ondragenter",
    },
    correctAnswer: "C",
  },
  {
    id: 74,
    text: "Which of the following attribute triggers event when an element has been dragged to a valid drop target?",
    options: {
      A: "ondragleave",
      B: "ondrag",
      C: "ondragend",
      D: "ondragenter",
    },
    correctAnswer: "D",
  },
  {
    id: 75,
    text: "Which of the following attribute triggers event when an element leaves a valid drop target?",
    options: {
      A: "ondrag",
      B: "ondragleave",
      C: "ondragover",
      D: "ondragstart",
    },
    correctAnswer: "B",
  },
  {
    id: 76,
    text: "Which of the following attribute triggers event when an element is being dragged over a valid drop target?",
    options: {
      A: "ondragleave",
      B: "ondrag",
      C: "ondragover",
      D: "ondragstart",
    },
    correctAnswer: "C",
  },
  {
    id: 77,
    text: "Which of the following attribute triggers event at the start of a drag operation?",
    options: {
      A: "ondragleave",
      B: "ondrag",
      C: "ondragover",
      D: "ondragstart",
    },
    correctAnswer: "D",
  },
  {
    id: 78,
    text: "Which of the following attribute triggers event when dragged element is being dropped?",
    options: {
      A: "ondrop",
      B: "ondurationchange",
      C: "onemptied",
      D: "onended",
    },
    correctAnswer: "A",
  },
  {
    id: 79,
    text: "Which of the following attribute triggers event when the length of the media is changed?",
    options: {
      A: "ondrop",
      B: "ondurationchange",
      C: "onemptied",
      D: "onended",
    },
    correctAnswer: "B",
  },
  {
    id: 80,
    text: "Which of the following attribute triggers event when a media resource element suddenly becomes empty?",
    options: {
      A: "ondrop",
      B: "ondurationchange",
      C: "onemptied",
      D: "onended",
    },
    correctAnswer: "C",
  },
  {
    id: 81,
    text: "Which of the following attribute triggers event when media has reach the end?",
    options: {
      A: "ondrop",
      B: "ondurationchange",
      C: "onemptied",
      D: "onended",
    },
    correctAnswer: "D",
  },
  {
    id: 82,
    text: "Which of the following attribute triggers event when an error occur?",
    options: {
      A: "onerror",
      B: "error",
      C: "onformerror",
      D: "onvalidation",
    },
    correctAnswer: "A",
  },
  {
    id: 83,
    text: "Which of the following attribute triggers event when the window gets focus?",
    options: {
      A: "focus",
      B: "onfocus",
      C: "onformchange",
      D: "onforminput",
    },
    correctAnswer: "B",
  },
  {
    id: 84,
    text: "Which of the following attribute triggers events when a form changes?",
    options: {
      A: "onchange",
      B: "onedit",
      C: "onformchange",
      D: "onforminput",
    },
    correctAnswer: "C",
  },
  {
    id: 85,
    text: "Which of the following attribute triggers events when a form gets user input?",
    options: {
      A: "onchange",
      B: "onedit",
      C: "onformchange",
      D: "onforminput",
    },
    correctAnswer: "D",
  },
  {
    id: 86,
    text: "Which of the following attribute triggers events when the document has change?",
    options: {
      A: "onhaschange",
      B: "oninput",
      C: "onchange",
      D: "onloadeddata",
    },
    correctAnswer: "A",
  },
  {
    id: 87,
    text: "Which of the following attribute triggers event when an element gets user input?",
    options: {
      A: "onhaschange",
      B: "oninput",
      C: "ondata",
      D: "onloadeddata",
    },
    correctAnswer: "B",
  },
  {
    id: 88,
    text: "Which of the following attribute triggers event when an element is invalid?",
    options: {
      A: "onhaschange",
      B: "oninput",
      C: "oninvalid",
      D: "onvalidate",
    },
    correctAnswer: "C",
  },
  {
    id: 89,
    text: "Which of the following attribute triggers event when media data is loaded?",
    options: {
      A: "onhaschange",
      B: "oninput",
      C: "onload",
      D: "onloadeddata",
    },
    correctAnswer: "D",
  },
  {
    id: 90,
    text: "Which of the following attribute triggers event when the duration and other media data of a media element is loaded?",
    options: {
      A: "onloadedmetadata",
      B: "onloadstart",
      C: "onmessage",
      D: "onoffline",
    },
    correctAnswer: "A",
  },
  {
    id: 91,
    text: "Which of the following attribute triggers event when the browser starts to load the media data?",
    options: {
      A: "onloadedmetadata",
      B: "onloadstart",
      C: "onmessage",
      D: "onoffline",
    },
    correctAnswer: "B",
  },
  {
    id: 92,
    text: "Which of the following attribute triggers event when the message is triggered?",
    options: {
      A: "onloadedmetadata",
      B: "onloadstart",
      C: "onmessage",
      D: "onoffline",
    },
    correctAnswer: "C",
  },
  {
    id: 93,
    text: "Which of the following attribute triggers event when the document goes offline?",
    options: {
      A: "onloadedmetadata",
      B: "onloadstart",
      C: "onmessage",
      D: "onoffline",
    },
    correctAnswer: "D",
  },
  {
    id: 94,
    text: "Which of the following attribute triggers event when media data is loaded?",
    options: {
      A: "onhaschange",
      B: "oninput",
      C: "onload",
      D: "onloadeddata",
    },
    correctAnswer: "D",
  },
  {
    id: 95,
    text: "Which of the following attribute triggers event when the document comes online?",
    options: {
      A: "onloadedmetadata",
      B: "onloadstart",
      C: "onmessage",
      D: "ononline",
    },
    correctAnswer: "D",
  },
  {
    id: 96,
    text: "Which of the following attribute triggers event when media can be played to the end, without stopping for buffering?",
    options: {
      A: "onbeforeplay",
      B: "onplay",
      C: "oncanplay",
      D: "oncanplaythrough",
    },
    correctAnswer: "D",
  },
  {
    id: 97,
    text: "Which of the following attribute triggers event when a context menu is triggered?",
    options: {
      A: "oncontextmenu",
      B: "ondrag",
      C: "ondragend",
      D: "ondragenter",
    },
    correctAnswer: "A",
  },
  {
    id: 98,
    text: "Which of the following attribute triggers event when the browser starts to load the media data?",
    options: {
      A: "onloadedmetadata",
      B: "onloadstart",
      C: "onmessage",
      D: "onoffline",
    },
    correctAnswer: "B",
  },
  {
    id: 99,
    text: "Which of the following attribute triggers event when the document goes offline?",
    options: {
      A: "onloadedmetadata",
      B: "onloadstart",
      C: "onmessage",
      D: "onoffline",
    },
    correctAnswer: "D",
  },
  {
    id: 100,
    text: "Which of the following attribute triggers event when the document comes online?",
    options: {
      A: "onloadedmetadata",
      B: "onloadstart",
      C: "onmessage",
      D: "ononline",
    },
    correctAnswer: "D",
  },
];
